import re

with open("validacao.html", "r") as f:
    html = f.read()

# UI Replacements
reps = {
    "My Plan": "Meu Plano",
    "WORKOUT SETTINGS": "CONFIGURAÇÕES DO TREINO",
    "Full Body": "Corpo Todo",
    "Gym": "Academia",
    "EXERCISES": "EXERCÍCIOS",
    "Edit ": "Editar ",
    "START WORKOUT": "INICIAR TREINO",
    "Workouts": "Treinos",
    "Explore pre-built plans in the real app.": "Explore planos pré-montados no app real.",
    "Progress": "Progresso",
    "WORKOUTS": "TREINOS",
    "Exercises": "Exercícios",
    "Profile": "Perfil",
    "SETTINGS": "CONFIGURAÇÕES",
    "Personal Info": "Informações Pessoais",
    "Equipments": "Equipamentos",
    "Sounds": "Sons",
    "Plan": "Plano",
    "Edit Workout Settings": "Editar Treino",
    "TARGET MUSCLE": "MÚSCULO ALVO",
    "DURATION": "DURAÇÃO",
    "Workout</div>": "Treino</div>",
    "CALORIES": "CALORIAS",
    "VOLUME (LBS)": "VOLUME (KG)",
    "Add exercise +": "Adicionar exercício +",
    "FINISH WORKOUT": "FINALIZAR TREINO",
    "W / WARM UP": "A / AQUECIMENTO",
    "SUPER SET": "SUPER SÉRIE",
    "3 sets • 10 reps": "3 séries • 10 reps",
    "<th>SET</th>": "<th>SÉRIE</th>",
    "<th>REPS</th>": "<th>REPS</th>",
    "<th>LBS</th>": "<th>KG</th>",
    "ADD SET": "ADICIONAR SÉRIE",
    "GOT IT": "ENTENDI",
    "Exercise Name": "Nome do Exercício",
    "MUSCLE • EQUIP": "MÚSCULO • EQUIPAMENTO",
    "Treino A (Peito, Ombro, Tríceps)": "Treino A (Peito, Ombro, Tríceps)",
    "Treino B (Costas, Bíceps)": "Treino B (Costas, Bíceps)",
    "Treino C (Pernas)": "Treino C (Pernas)",
    "Treino Core & Abs": "Treino Core & Abdômen",
}

for eng, pt in reps.items():
    html = html.replace(eng, pt)

# Database translation mapping
trans_dict = {
    '"chest"': '"peito"',
    '"back"': '"costas"',
    '"shoulders"': '"ombros"',
    '"arms"': '"braços"',
    '"legs"': '"pernas"',
    '"core"': '"abdômen"',
    '"abdominals"': '"abdômen"',
    '"hamstrings"': '"posteriores"',
    '"quadriceps"': '"quadríceps"',
    '"biceps"': '"bíceps"',
    '"triceps"': '"tríceps"',
    '"glutes"': '"glúteos"',
    '"calves"': '"panturrilhas"',
    '"middle back"': '"costas"',
    '"lats"': '"dorsais"',
    '"body only"': '"peso do corpo"',
    '"machine"': '"máquina"',
    '"kettlebells"': '"kettlebell"',
    '"dumbbell"': '"halter"',
    '"barbell"': '"barra"',
    '"cable"': '"cabo"',
    '"bands"': '"elástico"',
    '"exercise ball"': '"bola suíça"',
    '"e-z curl bar"': '"barra W"',
    '"medicine ball"': '"bola medicinal"',
    '"foam roll"': '"rolo de espuma"',
    '"None"': '"nenhum"',
}

for eng, pt in trans_dict.items():
    html = html.replace(eng, pt)

# Some basic exercise name translations inside EX_DB
names = {
    "Barbell Bench Press": "Supino Reto com Barra",
    "Butterfly": "Voador Peitoral",
    "Cable Crossover": "Crossover no Cabo",
    "Push-Up": "Flexão de Braço",
    "Cable Pull Down": "Puxada na Polia",
    "Barbell Bent Over Row": "Remada Curvada com Barra",
    "Dumbbell One Arm Row": "Remada Unilateral com Halter",
    "Chin-Up": "Barra Fixa Supinada",
    "Dumbbell Shoulder Press": "Desenvolvimento com Halteres",
    "Reverse Machine Flyes": "Crucifixo Invertido Máquina",
    "Barbell Curl": "Rosca Direta com Barra",
    "Dips - Triceps": "Mergulho para Tríceps",
    "EZ-Bar Skullcrusher": "Tríceps Testa Barra W",
    "Seated Triceps Press": "Tríceps Francês Sentado",
    "Triceps Rope Pushdown": "Tríceps Corda",
    "Barbell Squat": "Agachamento Livre",
    "Leg Press": "Leg Press",
    "Leg Extensions": "Cadeira Extensora",
    "Lying Leg Curls": "Mesa Flexora",
    "Barbell Glute Bridge": "Elevação Pélvica com Barra",
    "Seated Calf Raise": "Panturrilha Sentada",
    "Crunch": "Abdominal Curto",
    "Plank": "Prancha",
    "Hanging Leg Raise": "Elevação de Pernas Suspenso",
    "3/4 Sit-Up": "Abdominal 3/4",
    "90/90 Hamstring": "Alongamento Posterior 90/90",
    "Ab Crunch Machine": "Máquina Abdominal",
    "Advanced Kettlebell Windmill": "Moinho Avançado Kettlebell",
    "Air Bike": "Bicicleta no Ar",
    "All Fours Quad Stretch": "Alongamento Quadríceps",
    "Alternate Hammer Curl": "Rosca Martelo Alternada",
    "Alternate Heel Touchers": "Toque no Calcanhar Alternado",
    "Alternate Incline Dumbbell Curl": "Rosca Inclinada Alternada",
    "Alternating Cable Shoulder Press": "Desenvolvimento Alternado Cabo",
    "Alternating Deltoid Raise": "Elevação Frontal Alternada",
    "Alternating Floor Press": "Supino Chão Alternado",
    "Alternating Hang Clean": "Clean Suspenso Alternado",
    "Alternating Kettlebell Press": "Desenvolvimento Alternado Kettlebell",
    "Alternating Kettlebell Row": "Remada Alternada Kettlebell",
    "Alternating Renegade Row": "Remada Renegada",
    "Ankle Circles": "Rotação de Tornozelo",
    "Ankle On The Knee": "Tornozelo no Joelho",
    "Anti-Gravity Press": "Desenvolvimento Anti-Gravidade",
    "Arm Circles": "Rotação de Braços",
    "Arnold Dumbbell Press": "Desenvolvimento Arnold",
    "Around The Worlds": "Volta ao Mundo Peitoral",
    "Back Flyes - With Bands": "Crucifixo Invertido Elástico",
    "Backward Medicine Ball Throw": "Arremesso Trás Bola Medicinal",
    "Ball Leg Curl": "Flexão de Perna na Bola",
    "Band Good Morning": "Bom Dia com Elástico",
    "Band Skull Crusher": "Tríceps Testa Elástico",
    "Barbell Ab Rollout": "Roda Abdominal com Barra",
    "Barbell Full Squat": "Agachamento Profundo",
    "Barbell Hack Squat": "Agachamento Hack com Barra",
    "Barbell Hip Thrust": "Elevação Pélvica",
    "Barbell Lunge": "Avanço com Barra",
    "Barbell Side Split Squat": "Agachamento Lateral Barra",
    "Barbell Squat To A Bench": "Agachamento no Banco",
    "Bench Dips": "Mergulho no Banco",
    "Bench Press - Powerlifting": "Supino Reto Powerlifting",
    "Bench Press with Chains": "Supino com Correntes",
    "Bent-Arm Barbell Pullover": "Pullover Barra Braço Dobrado",
    "Bent-Arm Dumbbell Pullover": "Pullover Halter",
    "Bent Over Barbell Row": "Remada Curvada Barra",
    "Board Press": "Supino com Tábua",
    "Body-Up": "Body-Up Tríceps",
    "Bodyweight Flyes": "Crucifixo Peso Corporal",
    "Brachialis-SMR": "Liberação Braquial",
    "Butt Lift (Bridge)": "Ponte de Glúteos",
    "Cable Hammer Curls - Rope Attachment": "Rosca Martelo Cabo Corda",
    "Cable Incline Pushdown": "Puxada Inclinada Cabo",
    "Cable Incline Triceps Extension": "Extensão Tríceps Inclinada",
    "Cable Preacher Curl": "Rosca Scott Cabo",
    "Calf Press": "Panturrilha Máquina",
    "Calf Raise On A Dumbbell": "Panturrilha com Halter",
    "Calf Raises - With Bands": "Panturrilha com Elástico",
    "Calf Stretch": "Alongamento Panturrilha",
    "Catch and Overhead Throw": "Arremesso para Cima",
    "Clean": "Clean",
    "Clean Deadlift": "Levantamento Terra Clean",
    "Close-Grip Front Lat Pulldown": "Puxada Frontal Pegada Fechada",
    "Double Kettlebell Alternating Hang Clean": "Clean Alternado Kettlebell Duplo",
    "Downward Facing Balance": "Equilíbrio de Bruços",
    "Dumbbell Incline Row": "Remada Inclinada Halter",
    "Dynamic Back Stretch": "Alongamento Dinâmico Costas",
    "Elevated Cable Rows": "Remada Elevada Cabo",
    "Flutter Kicks": "Chute de Tesoura",
    "Glute Kickback": "Coice de Glúteo",
    "Hip Extension with Bands": "Extensão de Quadril Elástico",
    "Barbell Bench Press - Medium Grip": "Supino Reto com Barra",
    "Barbell Incline Bench Press - Medium Grip": "Supino Inclinado com Barra",
}

for eng, pt in names.items():
    html = html.replace(f'"{eng}"', f'"{pt}"')
    html = html.replace(f'>{eng}<', f'>{pt}<')

with open("validacao.html", "w") as f:
    f.write(html)
print("Translating finished")
